issues:
  # include:
  #   - EXC0004
  #   - EXC0005
  #   - EXC0011
  #   - EXC0012
  #   - EXC0013
  #   - EXC0014
  #   - EXC0015

linters:
  disable:
    - unused
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errname
    - errorlint
    - copyloopvar
    - forcetypeassert
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - tagliatelle
    - wastedassign
linters-settings:
  errorlint:
    errorf: true
  gosec:
    excludes:
      - G204
  gocognit:
    min-complexity: 50 # TODO: way too high, turn down later
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - commentedOutCode
  misspell:
    locale: US
  nolintlint:
    require-specific: true
    require-explanation: false
  tagliatelle:
    case:
      rules:
        json: snake
